name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Test with pytest
        run: |
          pytest tests/

  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          apt-get update && apt-get install -y pandoc texlive-latex-recommended      
          pandoc --filter pandoc-citeproc --bibliography=paper/paper.bib -s paper/paper.md -o paper/paper.pdf --template paper/latex.template

      - uses: actions/upload-artifact@v3
      - name: Upload
        with:
          name: paper
          path: paper/paper.pdf